# Generated by Django 2.2 on 2020-08-12 11:14

import app_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0004_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=app_core.models.recipe_image_file_path),
        ),
    ]
